INSERT INTO Menu (MENU_ID, MENU_CATEGORY, MENU_NAME, MENU_PRICE)
VALUES (1, 'SET_MENU', '불고기 버거 세트', 5700);
INSERT INTO Menu (MENU_ID, MENU_CATEGORY, MENU_NAME, MENU_PRICE)
VALUES (2, 'SET_MENU', '바베큐 버거 세트', 6200);
INSERT INTO Menu (MENU_ID, MENU_CATEGORY, MENU_NAME, MENU_PRICE)
VALUES (3, 'SET_MENU', '더블 쇠고기 버거 세트', 7700);
INSERT INTO Menu (MENU_ID, MENU_CATEGORY, MENU_NAME, MENU_PRICE)
VALUES (4, 'SET_MENU', '쇠고기 새우 버거 세트', 7200);
INSERT INTO Menu (MENU_ID, MENU_CATEGORY, MENU_NAME, MENU_PRICE)
VALUES (5, 'SET_MENU', '치킨 버거 세트', 6700);
INSERT INTO Menu (MENU_ID, MENU_CATEGORY, MENU_NAME, MENU_PRICE)
VALUES (6, 'SET_MENU', '새우 버거 세트', 6500);
INSERT INTO Menu (MENU_ID, MENU_CATEGORY, MENU_NAME, MENU_PRICE)
VALUES (7, 'BURGER', '불고기 버거', 3500);
INSERT INTO Menu (MENU_ID, MENU_CATEGORY, MENU_NAME, MENU_PRICE)
VALUES (8, 'BURGER', '바베큐 버거', 4000);
INSERT INTO Menu (MENU_ID, MENU_CATEGORY, MENU_NAME, MENU_PRICE)
VALUES (9, 'BURGER', '더블 쇠고기 버거', 5500);
INSERT INTO Menu (MENU_ID, MENU_CATEGORY, MENU_NAME, MENU_PRICE)
VALUES (10, 'BURGER', '쇠고기 새우 버거', 5000);
INSERT INTO Menu (MENU_ID, MENU_CATEGORY, MENU_NAME, MENU_PRICE)
VALUES (11, 'BURGER', '치킨 버거', 4500);
INSERT INTO Menu (MENU_ID, MENU_CATEGORY, MENU_NAME, MENU_PRICE)
VALUES (12, 'BURGER', '새우 버거', 4300);
INSERT INTO Menu (MENU_ID, MENU_CATEGORY, MENU_NAME, MENU_PRICE)
VALUES (13, 'DRINK', '오렌지 주스', 2500);
INSERT INTO Menu (MENU_ID, MENU_CATEGORY, MENU_NAME, MENU_PRICE)
VALUES (14, 'DRINK', '사이다', 1800);
INSERT INTO Menu (MENU_ID, MENU_CATEGORY, MENU_NAME, MENU_PRICE)
VALUES (15, 'DRINK', '코카콜라', 1800);
INSERT INTO Menu (MENU_ID, MENU_CATEGORY, MENU_NAME, MENU_PRICE)
VALUES (16, 'DRINK', '환타', 1800);
INSERT INTO Menu (MENU_ID, MENU_CATEGORY, MENU_NAME, MENU_PRICE)
VALUES (17, 'DRINK', '생수', 1000);
INSERT INTO Menu (MENU_ID, MENU_CATEGORY, MENU_NAME, MENU_PRICE)
VALUES (18, 'SIDE', '치킨 너겟', 2000);
INSERT INTO Menu (MENU_ID, MENU_CATEGORY, MENU_NAME, MENU_PRICE)
VALUES (19, 'SIDE', '감자튀김', 1800);
INSERT INTO Menu (MENU_ID, MENU_CATEGORY, MENU_NAME, MENU_PRICE)
VALUES (20, 'SIDE', '닭다리', 1500);
INSERT INTO Menu (MENU_ID, MENU_CATEGORY, MENU_NAME, MENU_PRICE)
VALUES (21, 'SIDE', '아이스크림 콘', 2500);
INSERT INTO Menu (MENU_ID, MENU_CATEGORY, MENU_NAME, MENU_PRICE)
VALUES (22, 'SIDE', '토마토 수프', 3000);
INSERT INTO Menu (MENU_ID, MENU_CATEGORY, MENU_NAME, MENU_PRICE)
VALUES (23, 'SIDE', '초코칩 쿠키', 1000);